version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data

  nodejs:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      - postgres
    env_file: .env
    environment:
      PORT: ${PORT}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./.docker/uploads:/app/uploads
    working_dir: /app
    command: ["npm", "run", "dev"]

volumes:
  postgres-data:
  uploads:
